[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Oblique" }
italic = { family = "JetBrainsMono Nerd Font", style = "Oblique" }

[scrolling]
history = 10000

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = true

[window.dimensions]
columns = 160
lines = 70
